### ISSUE TITLE
DataMatrix encoder throws IllegalArgumentException in ZXing 3.3.3

### ISSUE THREAD

**Issue by CyanPZ** [zxing/zxing#1058]
```
 String base64Image = null;
        try {
            Map<EncodeHintType, Object> config = new HashMap<>();
            config.put(EncodeHintType.CHARACTER_SET, "UTF-8");
            config.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
            config.put(EncodeHintType.DATA_MATRIX_SHAPE, SymbolShapeHint.FORCE_RECTANGLE);

            BitMatrix bitMatrix = new MultiFormatWriter().encode(data, BarcodeFormat.DATA_MATRIX, 200, 80, config);
            bitMatrix=deleteWhite(bitMatrix);
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            MatrixToImageWriter.writeToStream(bitMatrix, "png", outputStream);
            BASE64Encoder encoder = new BASE64Encoder();
            base64Image = "data:image/png;base64," + encoder.encode(outputStream.toByteArray());
            outputStream.close();
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }

        return base64Image;

```

```
java.lang.IllegalArgumentException: Can't find a symbol arrangement that matches the message. Data codewords: 52
	at com.google.zxing.datamatrix.encoder.SymbolInfo.lookup(SymbolInfo.java:148)
	at com.google.zxing.datamatrix.encoder.EncoderContext.updateSymbolInfo(EncoderContext.java:127)
	at com.google.zxing.datamatrix.encoder.EncoderContext.updateSymbolInfo(EncoderContext.java:122)
	at com.google.zxing.datamatrix.encoder.HighLevelEncoder.encodeHighLevel(HighLevelEncoder.java:189)
	at com.google.zxing.datamatrix.DataMatrixWriter.encode(DataMatrixWriter.java:84)
	at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
```

**Comment by srowen** [comment]
(Maybe a better title about the specific error?)
Hm, I don't know. Is it that you're constraining the shape of the symbol and that means it can't find a supported size? If so, not sure if that's a problem. What change would you propose?

**Comment by CyanPZ** [comment]
Thank you.  I am sorry about that , i try again, it works
