### ISSUE TITLE
Camera._stopPreview error

### ISSUE THREAD

**Issue by lxykad** [zxing/zxing#1085]
only on oppo phone report this error:

`java.lang.RuntimeException: stop face detection failed
	at android.hardware.Camera._stopPreview(Native Method)
	at android.hardware.Camera.stopPreview(Camera.java:925)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
	at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4199)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4176)
	at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4145)
	at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4119)
	at android.app.ActivityThread.-wrap15(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1814)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:187)
	at android.app.ActivityThread.main(ActivityThread.java:7021)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:514)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)`
so,why?

**Comment by srowen** [comment]
This is an Android error, not from the app

**Comment by lxykad** [comment]
> This is an Android error, not from the app

thx
