### ISSUE TITLE
'€' unable to write character '€' using BarcodeWriter.Write() method

### ISSUE THREAD

**Issue by bharatbodage** [zxing/zxing#1131]
'€' unable to write character '€' using BarcodeWriter.Write() method
it throws exception: 
InnnerException: Non-encodable character detected: € (Unicode: 8364)
Stack Trace:    at ZXing.PDF417.Internal.PDF417HighLevelEncoder.determineConsecutiveBinaryCount(String msg, Byte[] bytes, Int32 startpos, Encoding encoding)
   at ZXing.PDF417.Internal.PDF417HighLevelEncoder.encodeHighLevel(String msg, Compaction compaction, Encoding encoding, Boolean disableEci)
   at ZXing.PDF417.Internal.PDF417.generateBarcodeLogic(String msg, Int32 errorCorrectionLevel, Int32 longDimension, Int32 shortDimension, Int32& aspectRatio)
   at ZXing.PDF417.PDF417Writer.bitMatrixFromEncoder(PDF417 encoder, String contents, Int32 errorCorrectionLevel, Int32 width, Int32 height, Int32 margin, Int32 aspectRatio)
   at ZXing.PDF417.PDF417Writer.encode(String contents, BarcodeFormat format, Int32 width, Int32 height, IDictionary`2 hints)
   at ZXing.MultiFormatWriter.encode(String contents, BarcodeFormat format, Int32 width, Int32 height, IDictionary`2 hints)
   at ZXing.BarcodeWriterGeneric.Encode(String contents)
   at ZXing.BarcodeWriter`1.Write(String contents)

**Comment by srowen** [comment]
That looks like a different library in .NET
