### ISSUE TITLE
java.lang.NoSuchMethodError: No interface method sort

### ISSUE THREAD

**Issue by D10NGYANG** [zxing/zxing#1171]
### Bug Reports
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
        at com.dlong.qrcodetest.zxing.DecodeHandler.decode(DecodeHandler.java:85)
        at com.dlong.qrcodetest.zxing.DecodeHandler.handleMessage(DecodeHandler.java:61)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at com.dlong.qrcodetest.zxing.DecodeThread.run(DecodeThread.java:111)

**Comment by srowen** [comment]
You're not using Java 8 / API 24 then.
