### ISSUE TITLE
In Android API 21 (Lollipop) it is crashing when scanning the QR code

### ISSUE THREAD

**Issue by usmanrana07** [zxing/zxing#1181]
In Android API 21 (Lollipop) it is crashing when scanning the QR code and giving following Logs:

```
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
```

**Comment by Pablohn26** [comment]
Your [pull request](https://github.com/zxing/zxing/pull/1180) is related to that :)

**Comment by usmanrana07** [comment]
Yes, I thought the error logs here will help to understand the issue better for the one who will review the pull request.
