### ISSUE TITLE
Getting issue in generating tag using specific non printable character with  barcode format code 128

### ISSUE THREAD

**Issue by RG108** [zxing/zxing#1188]
Hi Guys,
I am generating  tag with barcode format code 128 which has the requirement like below:
I have to create a tag using non-printable characters whose ASCII value are 16, 189 or 229, 17
So, while consuming Zxing library it fails and gives the below error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Bad character in input: ½
	at com.google.zxing.oned.Code128Writer.encode(Code128Writer.java:95)
	at com.google.zxing.oned.OneDimensionalCodeWriter.encode(OneDimensionalCodeWriter.java:69)
	at com.google.zxing.oned.Code128Writer.encode(Code128Writer.java:72)
	at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:102)
	at com.cextools.Sample.main(Sample.java:133)

```
Can someone please help me in solving this issue. I am deeply stuck due to this.

**Comment by srowen** [comment]
You should be able to pass a string with those non-printable chars, but the '1/2' character isn't one of them. I think there's a problem with how you are forming your input string.
