### ISSUE TITLE
Crash app when scanning barcode in version 3.4.0

### ISSUE THREAD

**Issue by nguyenduyanhuit** [zxing/zxing#1189]
I try scan barcode in version 3.4.0, device below API level 24 always crash app. Please help me!!!

This is log when crash app:

java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
        at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
        at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
        at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:137)
        at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
        at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:194)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by feb07** [comment]
the same problem！same crash log

**Comment by srowen** [comment]
Yes, because 3.4.0 requires API 24.
