### ISSUE TITLE
Spaces not allowed in CommandLineRunner with --possible_formats flag

### ISSUE THREAD

**Issue by Cody-G** [zxing/zxing#1219]
Exception below:

```
Exception in thread "main" java.net.URISyntaxException: Illegal character in path at index 18: --possible_formats DATA_MATRIX
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
	at java.base/java.net.URI$Parser.parse(URI.java:3127)
	at java.base/java.net.URI.<init>(URI.java:600)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:64)
```
Possibly related to #540?

I'm also inserting a flag afterward as discussed in #665 so I don't think that's the problem.  Thanks!

(running v3.4.0)

**Comment by srowen** [comment]
What is your command line? the error says it thinks this is the URI.

**Comment by Cody-G** [comment]
My mistake sorry, this was a problem with the [python-zxing](https://github.com/oostendo/python-zxing) wrapper.  It was confusing to debug because the command worked fine until it was sent to the python subprocess.  Command is below for reference

```
java -cp /home/cody/src/zxing-zxing-3.4.0/javase/target/javase-3.4.0-jar-with-dependencies.jar com.google.zxing.client.j2se.CommandLineRunner --multi --possible_formats DATA_MATRIX --try_harder data_matrix_and_QR.jpg
```

Thanks for the great library!
