### ISSUE TITLE
miss detection of finder patterns

### ISSUE THREAD

**Issue by lscgzwd** [zxing/zxing#1248]
Thanks.

Please look at this issue:

https://github.com/makiuchi-d/gozxing/issues/27

the qrcode post on that issue, can not be recognize.

CommandLineRunner shows not found:
```
$ java -cp ~/Downloads/javase-3.4.0.jar:~/Downloads/core-3.4.0.jar:api/vendor/dsiddharth2/php-zxing/src/bin/jcommander-1.72.jar com.google.zxing.client.j2se.CommandLineRunner ~/Downloads/q2.png
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/zxing/NotFoundException
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:99)
Caused by: java.lang.ClassNotFoundException: com.google.zxing.NotFoundException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```

**Comment by srowen** [comment]
Please read the text you removed.
Also, this works: https://zxing.org/w/decode?u=https%3A%2F%2Fpyds.oss-cn-beijing.aliyuncs.com%2Fuploads%2Ftest-data%2F2019-11-13%2Fdeskewed%2F09e0789b-8ada-4ff4-bc81-3339c805eedf.png

**Comment by lscgzwd** [comment]
there are two qrcode image. all can not decode by CommandLineRunner. Also this one not works with online decode:  https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F7054255%2F68769398-30496e80-065f-11ea-9b85-5011cd16d821.png
it says: no barcode was found
