### ISSUE TITLE
How to open the project? [question]

### ISSUE THREAD

**Issue by c0dd3vi11** [zxing/zxing#1257]
Hello, dear developer!

I'm totally new in android development. I'm using Android Studio and don't know how to open this project (to build the android-application: https://f-droid.org/en/packages/com.google.zxing.client.android/).

I see that it's using Maven and I need or InteliJ IDEA, or convert it to Gradle. But it won't open in IDEA too, or (that is more likely) I don't know ho to do it properly.

Could you help me and lead a little to how to build the application, please? ^_^

p.s. I have a lot experience in iOS-development, but it seems that it doesn't helps at all :D

**Comment by srowen** [comment]
It should open directly. It's a Maven project. It works fine in IDEA.

**Comment by c0dd3vi11** [comment]
<img width="1135" alt="Screenshot 2020-01-31 at 20 05 44" src="https://user-images.githubusercontent.com/60510579/73558957-3af8f000-4465-11ea-901a-a60f4d8f716c.png">
I opened the root and... nothing happened. No configurations and nothing happen when I press build button.

**Comment by srowen** [comment]
See the notification at the bottom right!

**Comment by c0dd3vi11** [comment]
If i press "Configure" the screen changes a little:
<img width="1023" alt="Screenshot 2020-01-31 at 20 11 40" src="https://user-images.githubusercontent.com/60510579/73559383-f91c7980-4465-11ea-9ac9-60b4111d1171.png">

**Comment by srowen** [comment]
Yes, you're done. You need to actually expand the project root at the left.
This isn't a question about the project, just basic IntelliJ usage.

**Comment by c0dd3vi11** [comment]
Yeees.. I told you, I am new in android development and just tried to use something out of a box...

But I think that I figured out what to do next... I made an Android Application configuration and now I'm trying to connect Android Studio's Android SDK to IDEA to build the app.
<img width="808" alt="Screenshot 2020-01-31 at 20 22 36" src="https://user-images.githubusercontent.com/60510579/73560115-6ed51500-4467-11ea-9238-0a30cc60fb0f.png">

**Comment by c0dd3vi11** [comment]
Too complicated...
<img width="1118" alt="Screenshot 2020-01-31 at 20 50 20" src="https://user-images.githubusercontent.com/60510579/73562060-62eb5200-446b-11ea-9a7b-8dabd2b1047a.png">
`Error:Internal error: (java.lang.ClassNotFoundException) javax.xml.bind.annotation.XmlSchema
java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:157)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:76)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:82)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidTarget(AndroidJpsUtil.java:405)
	at org.jetbrains.jps.android.AndroidJpsUtil.getAndroidPlatform(AndroidJpsUtil.java:481)
	at org.jetbrains.jps.android.builder.AndroidPreDexBuildTarget.computeRootDescriptors(AndroidPreDexBuildTarget.java:111)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.addRoots(BuildRootIndexImpl.java:72)
	at org.jetbrains.jps.builders.impl.BuildRootIndexImpl.<init>(BuildRootIndexImpl.java:62)
	at org.jetbrains.jps.cmdline.BuildRunner.load(BuildRunner.java:83)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:274)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:130)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:232)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)`

**Comment by srowen** [comment]
I works fine, I assure you. I use IJ for this project all the time. You probably have Java 11 specified for the project (?) when it needs Java 8.

**Comment by c0dd3vi11** [comment]
Yes, I installed JDK 13.0.2. I'll try to install 8th version.

**Comment by c0dd3vi11** [comment]
I woke up earlier to try again and IDEA finally found the JDK 1.8! After Nth IDE restarting and 8 hours in sleep mode :D

And now I'm here:
<img width="1224" alt="Screenshot 2020-02-01 at 08 06 34" src="https://user-images.githubusercontent.com/60510579/73587216-4e8a7200-44ca-11ea-906a-6fe27cb3a2ed.png">

1. Changed ${env.JAVA_HOME} to the real path.
2. Changed android.platform to 28.
