### ISSUE TITLE
Bug error on CaptureManager initalization

### ISSUE THREAD

**Issue by jovdelfin01** [zxing/zxing#1269]
Hi guys so basically I am trying to put the flashlight with the scanner and I copied the code from CustomScannerActivity to my own activity. I converted it from java to kolin however it is erroring out in the initialization "capture = CaptureManager(this, barcodeScannerView)"

When I looked inside it was erroring on this part

`inactivityTimer = new InactivityTimer(activity, () -> {
            Log.d(TAG, "Finishing due to inactivity");
            finish();
        });`

Here is my intent code to go to the activity

`IntentIntegrator(activity).setOrientationLocked(false).setDesiredBarcodeFormats(IntentIntegrator.CODE_39).setCaptureActivity(ScannerActivity::class.java).initiateScan()
`

and here is my full activity code. Please help.

`class ScannerActivity : Activity(), DecoratedBarcodeView.TorchListener {

    private var capture: CaptureManager? = null
    private var barcodeScannerView: DecoratedBarcodeView? = null
    private lateinit var switchFlashlightButton: Button
    private lateinit var viewfinderView: ViewfinderView

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_scanner)

        barcodeScannerView = zxing_barcode_scanners
        barcodeScannerView?.setTorchListener(this)

        switchFlashlightButton = switch_flashlight
        viewfinderView = zxing_viewfinder_view

        if (!hasFlash()) {
            switchFlashlightButton.setVisibility(View.GONE)
        }

        capture = CaptureManager(this, barcodeScannerView)
        capture?.initializeFromIntent(intent, savedInstanceState)
        capture?.setShowMissingCameraPermissionDialog(true)
        capture?.decode()

        changeMaskColor(null)
        changeLaserVisibility(true)
    }

    override fun onResume() {
        super.onResume()
        capture?.onResume()
    }

    override fun onPause() {
        super.onPause()
        capture?.onPause()
    }

    override fun onDestroy() {
        super.onDestroy()
        capture?.onDestroy()
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        capture?.onSaveInstanceState(outState)
    }

    override fun onKeyDown(keyCode: Int, event: KeyEvent): Boolean {
        return barcodeScannerView!!.onKeyDown(keyCode, event) || super.onKeyDown(keyCode, event)
    }

    private fun hasFlash(): Boolean {
        return applicationContext.packageManager
            .hasSystemFeature(PackageManager.FEATURE_CAMERA_FLASH)
    }

    fun switchFlashlight(view: View) {
        if (getString(R.string.turn_on_flashlight) == switchFlashlightButton.getText()) {
            barcodeScannerView!!.setTorchOn()
        } else {
            barcodeScannerView!!.setTorchOff()
        }
    }

    fun changeMaskColor(view: View?) {
        val rnd = Random()
        val color = Color.argb(100, rnd.nextInt(256), rnd.nextInt(256), rnd.nextInt(256))
        viewfinderView.setMaskColor(color)
    }

    fun changeLaserVisibility(visible: Boolean) {
        viewfinderView.setLaserVisibility(visible)
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)

        capture?.onRequestPermissionsResult(requestCode, permissions, grantResults)
    }

    override fun onTorchOn() {
        switchFlashlightButton.setText(R.string.turn_off_flashlight)
    }

    override fun onTorchOff() {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
        switchFlashlightButton.setText(R.string.turn_on_flashlight)
    }
}`

**Comment by srowen** [comment]
You are asking about your own code, and haven't even shown the error.

**Comment by jovdelfin01** [comment]
I'm sorry. This was the error

`2020-03-22 06:39:11.637 29024-29024/com.elevintech.disappeardents E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.elevintech.disappeardents, PID: 29024
    java.lang.BootstrapMethodError: Exception from call site #4 bootstrap method
        at com.journeyapps.barcodescanner.CaptureManager.<init>(CaptureManager.java:130)
        at com.elevintech.disappeardents.CreateQuote.Scanner.ScannerActivity.onCreate(ScannerActivity.kt:42)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3259)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7073)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.journeyapps.barcodescanner.CaptureManager.<init>(CaptureManager.java:130) 
        at com.elevintech.disappeardents.CreateQuote.Scanner.ScannerActivity.onCreate(ScannerActivity.kt:42) 
        at android.app.Activity.performCreate(Activity.java:7327) 
        at android.app.Activity.performCreate(Activity.java:7318) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3259) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7073) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
`
