### ISSUE TITLE
This bug occurs when printing some combination of characters: data bits cannot fit in the QR Code448 > 440

### ISSUE THREAD

**Issue by DHHHhhhe** [zxing/zxing#1271]
W/System.err: com.google.zxing.WriterException: data bits cannot fit in the QR Code448 > 440
 W/System.err:     at com.google.zxing.qrcode.encoder.Encoder.terminateBits(Encoder.java:281)
 W/System.err:     at com.google.zxing.qrcode.encoder.Encoder.encode(Encoder.java:120)
 W/System.err:     at com.google.zxing.qrcode.QRCodeWriter.encode(QRCodeWriter.java:76)
 W/System.err:     at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:86)
 W/System.err:     at com.lanlnk.hongsen.printutil.BarcodeCreater.encodeAsBitmap(BarcodeCreater.java:188)
 W/System.err:     at com.lanlnk.hongsen.printutil.BarcodeCreater.encode2dAsBitmap(BarcodeCreater.java:141)
 W/System.err:     at com.lanlnk.hongsen.printutil.BitmapPrinter.addQrcode(BitmapPrinter.java:52)
 W/System.err:     at com.lanlnk.hongsen.printutil.ProcurePrint.inputPrint(ProcurePrint.java:66)
 W/System.err:     at com.lanlnk.hongsen.adapter.ListCaigouAdapter.lambda$getView$0$ListCaigouAdapter(ListCaigouAdapter.java:124)
 W/System.err:     at com.lanlnk.hongsen.adapter.-$$Lambda$ListCaigouAdapter$N0MYRfvZov93zSYGsBQ_x-Ff27c.onClick(lambda)
 W/System.err:     at android.view.View.performClick(View.java:5265)
 W/System.err:     at android.view.View$PerformClick.run(View.java:21534)
 W/System.err:     at android.os.Handler.handleCallback(Handler.java:815)
 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:104)
 W/System.err:     at android.os.Looper.loop(Looper.java:207)
 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5765)
 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
 W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
 D/AndroidRuntime: Shutting down VM
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.lanlnk.hongsen, PID: 5434
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
        at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1269)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
        at com.lanlnk.hongsen.printutil.BitmapPrinter.addQrcode(BitmapPrinter.java:53)
        at com.lanlnk.hongsen.printutil.ProcurePrint.inputPrint(ProcurePrint.java:66)
        at com.lanlnk.hongsen.adapter.ListCaigouAdapter.lambda$getView$0$ListCaigouAdapter(ListCaigouAdapter.java:124)
        at com.lanlnk.hongsen.adapter.-$$Lambda$ListCaigouAdapter$N0MYRfvZov93zSYGsBQ_x-Ff27c.onClick(lambda)
        at android.view.View.performClick(View.java:5265)
        at android.view.View$PerformClick.run(View.java:21534)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5765)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by srowen** [comment]
Hard to say without any clue about a reproduction.

**Comment by DHHHhhhe** [comment]
For example, print this set of characters:PHAJ095T2011-30T&tab20181220&tab12.20&tab码&tabA&tab

**Comment by DHHHhhhe** [comment]
> Hard to say without any clue about a reproduction.

For example, print this set of characters:PHAJ095T2011-30T&tab20181220&tab12.20&tab码&tabA&tab
