### ISSUE TITLE
no List.sort method in some Android device

### ISSUE THREAD

**Issue by nekohasekai** [zxing/zxing#1272]
```
Fatal Exception: java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
       at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
       at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
       at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
       at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
       at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:64)
       at com.example.QRReadTest.tryReadQR(QRReadTest.java:407)
```

device: `OPPO A33m / android  5.1.1`

**Comment by srowen** [comment]
You are not using a new enough version of Android

**Comment by nekohasekai** [comment]
@srowen I am using core 1.4.0, is it an old version?

**Comment by nekohasekai** [comment]
But I don't think android5 is very old, and this is not my device.

**Comment by zuijiusi** [comment]
just use 3.3.3；3.4.0 is not support

**Comment by SJpro** [comment]
> But I don't think android5 is very old, and this is not my device.

just one line code can support low version android device
