### ISSUE TITLE
GenericMultipleBarcodeReader  java.lang.ArrayIndexOutOfBoundsException: length=7216; index=7216

### ISSUE THREAD

**Issue by changjiashuai** [zxing/zxing#1342]
Zxing Version: 3.4.1

2020-12-30 16:37:26.267 21628-21628/com.google.mlkit.vision.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.mlkit.vision.demo, PID: 21628
    java.lang.ArrayIndexOutOfBoundsException: length=7216; index=7216
        at com.google.zxing.common.BitMatrix.get(BitMatrix.java:162)
        at com.google.zxing.maxicode.MaxiCodeReader.extractPureBits(MaxiCodeReader.java:104)
        at com.google.zxing.maxicode.MaxiCodeReader.decode(MaxiCodeReader.java:64)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:71)
        at com.google.zxing.multi.GenericMultipleBarcodeReader.doDecodeMultiple(GenericMultipleBarcodeReader.java:86)
        at com.google.zxing.multi.GenericMultipleBarcodeReader.doDecodeMultiple(GenericMultipleBarcodeReader.java:139)
        at com.google.zxing.multi.GenericMultipleBarcodeReader.doDecodeMultiple(GenericMultipleBarcodeReader.java:132)
        at com.google.zxing.multi.GenericMultipleBarcodeReader.decodeMultiple(GenericMultipleBarcodeReader.java:67)
        at com.google.zxing.multi.GenericMultipleBarcodeReader.decodeMultiple(GenericMultipleBarcodeReader.java:60)
        at com.google.mlkit.vision.demo.kotlin.barcodescanner.ZxingMultipleBarcodeProcessor.detectInImage(ZxingMultipleBarcodeProcessor.kt:40)
        at com.google.mlkit.vision.demo.kotlin.VisionProcessorBase.requestDetectInImage(VisionProcessorBase.kt:210)
        at com.google.mlkit.vision.demo.kotlin.VisionProcessorBase.processImageProxy(VisionProcessorBase.kt:188)
        at com.google.mlkit.vision.demo.kotlin.CameraXLivePreviewActivity$bindAnalysisUseCase$1.analyze(CameraXLivePreviewActivity.kt:453)
        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$1$ImageAnalysis(ImageAnalysis.java:349)
        at androidx.camera.core.-$$Lambda$ImageAnalysis$SK4XUin3LEuOy83vccLKZvMIwq8.analyze(Unknown Source:4)
        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:87)
        at androidx.camera.core.-$$Lambda$ImageAnalysisAbstractAnalyzer$V6Gtux2-h8spda8vf4wFnIZntYI.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by srowen** [comment]
Do you have a barcode that reproduces this?

**Comment by srowen** [comment]
I took a decent guess at the cause of this after reviewing the code:
https://github.com/zxing/zxing/commit/6dd0776b961f8471c8cd9df7b49d6652c4629175

**Comment by changjiashuai** [comment]
![IMG_20201231_102552](https://user-images.githubusercontent.com/4496625/103391179-000aab00-4b53-11eb-9a35-a5457c25ce4c.jpg)

This is the qr code, you can try to scan it many times and it may happen.

**Comment by srowen** [comment]
That actually decodes just fine as  `http://weixin.qq.com/r/_3TcxNLENo9JrZan9yHp`. The problem is that the Maxi Code reader ends up producing an error on this image, even though there is no such barcode in there. The commit I just made may fix it, or at least, that's my best guess at how the error can occur.
