### ISSUE TITLE
NullPointerExceptionat com.google.zxing.client.android.book.SearchBookContentsActivity.onCreate(SearchBookContentsActivity.java:100)

### ISSUE THREAD

**Issue by JagdeepSingh28** [zxing/zxing#1406]
Hi I am getting the below error in my firebase crash logs

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
       at com.google.zxing.client.android.book.SearchBookContentsActivity.onCreate(SearchBookContentsActivity.java:100)
       at android.app.Activity.performCreate(Activity.java:8006)
       at android.app.Activity.performCreate(Activity.java:7990)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3580)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3771)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2242)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:245)
       at android.app.ActivityThread.main(ActivityThread.java:8004)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

I am not even calling SearchBookContentsActivity anywhere from the application. Can anybody help me find the reason behind this error?

**Comment by srowen** [comment]
Hm, there is no .equals() on that line in the latest code, even. The one near it can't produce an NPE as it calls .equals on a constant string. Have you modified the code or anything? It could be something weird to do with Android but can't see how it happens with the library.
