### ISSUE TITLE
Getting this error from console 

### ISSUE THREAD

**Issue by ninesoltech** [zxing/zxing#1467]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qrreader.qrcodescanner.barcodereader.freebarcodescanner/com.yzq.zxinglibrary.android.CaptureActivity}: java.lang.RuntimeException: Failed to call observer method
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by srowen** [comment]
Not sure, that code is not from this project.
