### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by RajnishGowreesunker** [zxing/zxing#1505]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10368; index=10368
       at com.google.zxing.common.BitMatrix.get(BitMatrix.java:162)
       at com.google.zxing.maxicode.MaxiCodeReader.extractPureBits(MaxiCodeReader.java:104)
       at com.google.zxing.maxicode.MaxiCodeReader.decode(MaxiCodeReader.java:64)
       at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
       at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
       at com.budiyev.android.codescanner.Utils.decodeLuminanceSource(Utils.java:342)
       at com.budiyev.android.codescanner.DecodeTask.decode(DecodeTask.java:75)
       at com.budiyev.android.codescanner.Decoder$DecoderThread.run(Decoder.java:133)

**Comment by thestinger** [comment]
I think this is fixed by https://github.com/zxing/zxing/commit/6dd0776b961f8471c8cd9df7b49d6652c4629175 and it looks like @srowen is working on a 3.5.0 release.
