### ISSUE TITLE
Corrupt image causes ArrayIndexOutOfBounds crash

### ISSUE THREAD

**Issue by kristianvld** [zxing/zxing#1533]
I'm using zxing in a research project involving image transformations and QR code extraction and think I have come across a strange edge case. At one point I had this one image that caused the program to crash with the following stack trace:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 4896 out of bounds for length 4896
        at com.google.zxing.common.BitMatrix.get(BitMatrix.java:74)
        at com.google.zxing.qrcode.QRCodeReader.extractPureBits(QRCodeReader.java:184)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:73)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
        at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:69)
        at com.google.zxing.multi.GenericMultipleBarcodeReader.doDecodeMultiple(GenericMultipleBarcodeReader.java:84)
        at com.google.zxing.multi.GenericMultipleBarcodeReader.doDecodeMultiple(GenericMultipleBarcodeReader.java:141)
        at com.google.zxing.multi.GenericMultipleBarcodeReader.decodeMultiple(GenericMultipleBarcodeReader.java:65)
        at com.google.zxing.client.j2se.DecodeWorker.decodeMulti(DecodeWorker.java:181)
        at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:76)
        at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:126)
```

Opening the following image with the command causes zxing to fail with the stack trace above:
```bash
zxing --try_harder --multi --pure_barcode crash.png
```

![crash](https://user-images.githubusercontent.com/7207116/171906987-7be4089e-fcbd-43ac-953b-f4122c4b0233.png)

As you can see from the image, it is too heavily corrupted to be interpreted as a QR code, and I did not expect it to work. Using other arguments, causes normal behavior where the program exits normally simply stating that it was unable to find a bar code instead of crashing.

**Comment by srowen** [comment]
This image doesn't seem to fail in that way in the latest code:
https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F7207116%2F171906987-7be4089e-fcbd-43ac-953b-f4122c4b0233.png

It misdetects some RSS14 barcode, so a different failure mode.
Are you trying the latest version? because there were a number of corner case fixes like this recently

**Comment by kristianvld** [comment]
Ah, sorry, should probably have made sure I was on the latest version first. I'm using nix for my project and seems the latest version in the nix package manager is 3.1.0:
https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/tools/graphics/zxing/default.nix#L4=

Thank you for your time, but if it is fixed in the latest version, then this can probably be closed.
