### ISSUE TITLE
Deadlock on the j2se GUI

### ISSUE THREAD

**Issue by emilianbold** [zxing/zxing#1564]
`com.google.zxing.client.j2se.GUIRunner` opens a very basic Swing window.

On OpenJDK 11 / macOS it enters into a deadlock because the window is opened in the main thread and not in the Event Queue thread.

The solution seems simple: follow Swing best practices and surround GUI initialisation code using `SwingUtilities.invokeLater` https://docs.oracle.com/javase/tutorial/uiswing/concurrency/initial.html

```
Java stack information for the threads listed above:
===================================================
"main":
	at com.apple.laf.AquaFileSystemModel.getRowCount(java.desktop@11.0.3/AquaFileSystemModel.java:204)
	- waiting to lock <0x000000070f7ee440> (a java.lang.Object)
	at javax.swing.JTable.getRowCount(java.desktop@11.0.3/JTable.java:2650)
	at javax.swing.plaf.basic.BasicTableUI.createTableSize(java.desktop@11.0.3/BasicTableUI.java:1732)
	at javax.swing.plaf.basic.BasicTableUI.getPreferredSize(java.desktop@11.0.3/BasicTableUI.java:1773)
	at javax.swing.JComponent.getPreferredSize(java.desktop@11.0.3/JComponent.java:1680)
	at javax.swing.ScrollPaneLayout.preferredLayoutSize(java.desktop@11.0.3/ScrollPaneLayout.java:499)
	at java.awt.Container.preferredSize(java.desktop@11.0.3/Container.java:1823)
	- locked <0x000000070fe8f6e8> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.getPreferredSize(java.desktop@11.0.3/Container.java:1807)
	at javax.swing.JComponent.getPreferredSize(java.desktop@11.0.3/JComponent.java:1682)
	at java.awt.BorderLayout.preferredLayoutSize(java.desktop@11.0.3/BorderLayout.java:724)
	- locked <0x000000070fe8f6e8> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.preferredSize(java.desktop@11.0.3/Container.java:1823)
	- locked <0x000000070fe8f6e8> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.getPreferredSize(java.desktop@11.0.3/Container.java:1807)
	at javax.swing.JComponent.getPreferredSize(java.desktop@11.0.3/JComponent.java:1682)
	at java.awt.BorderLayout.preferredLayoutSize(java.desktop@11.0.3/BorderLayout.java:724)
	- locked <0x000000070fe8f6e8> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.preferredSize(java.desktop@11.0.3/Container.java:1823)
	- locked <0x000000070fe8f6e8> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.getPreferredSize(java.desktop@11.0.3/Container.java:1807)
	at javax.swing.JComponent.getPreferredSize(java.desktop@11.0.3/JComponent.java:1682)
	at javax.swing.BoxLayout.checkRequests(java.desktop@11.0.3/BoxLayout.java:480)
	at javax.swing.BoxLayout.layoutContainer(java.desktop@11.0.3/BoxLayout.java:421)
	- locked <0x000000070f78a270> (a javax.swing.BoxLayout)
	at java.awt.Container.layout(java.desktop@11.0.3/Container.java:1537)
	at java.awt.Container.doLayout(java.desktop@11.0.3/Container.java:1526)
	at java.awt.Container.validateTree(java.desktop@11.0.3/Container.java:1722)
	at java.awt.Container.validateTree(java.desktop@11.0.3/Container.java:1731)
	at java.awt.Container.validateTree(java.desktop@11.0.3/Container.java:1731)
	at java.awt.Container.validateTree(java.desktop@11.0.3/Container.java:1731)
	at java.awt.Container.validateTree(java.desktop@11.0.3/Container.java:1731)
	at java.awt.Container.validate(java.desktop@11.0.3/Container.java:1657)
	- locked <0x000000070fe8f6e8> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.validateUnconditionally(java.desktop@11.0.3/Container.java:1694)
	- locked <0x000000070fe8f6e8> (a java.awt.Component$AWTTreeLock)
	at java.awt.Window.pack(java.desktop@11.0.3/Window.java:835)
	at javax.swing.JFileChooser.createDialog(java.desktop@11.0.3/JFileChooser.java:819)
	at javax.swing.JFileChooser.showDialog(java.desktop@11.0.3/JFileChooser.java:747)
	at javax.swing.JFileChooser.showOpenDialog(java.desktop@11.0.3/JFileChooser.java:653)
	at com.google.zxing.client.j2se.GUIRunner.chooseImage(GUIRunner.java:79)
	at com.google.zxing.client.j2se.GUIRunner.main(GUIRunner.java:74)
"AWT-EventQueue-0":
	at java.awt.Component.invalidate(java.desktop@11.0.3/Component.java:3016)
	- waiting to lock <0x000000070fe8f6e8> (a java.awt.Component$AWTTreeLock)
	at java.awt.Container.invalidate(java.desktop@11.0.3/Container.java:1614)
	at javax.swing.JComponent.revalidate(java.desktop@11.0.3/JComponent.java:4891)
	at javax.swing.JTable.tableRowsInserted(java.desktop@11.0.3/JTable.java:4487)
	at javax.swing.JTable.tableChanged(java.desktop@11.0.3/JTable.java:4412)
	at javax.swing.table.AbstractTableModel.fireTableChanged(java.desktop@11.0.3/AbstractTableModel.java:297)
	at javax.swing.table.AbstractTableModel.fireTableRowsInserted(java.desktop@11.0.3/AbstractTableModel.java:232)
	at com.apple.laf.AquaFileSystemModel$DoChangeContents.run(java.desktop@11.0.3/AquaFileSystemModel.java:477)
	- locked <0x000000070f7ee440> (a java.lang.Object)
	- locked <0x000000070f410740> (a java.lang.Object)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@11.0.3/InvocationEvent.java:313)
	at java.awt.EventQueue.dispatchEventImpl(java.desktop@11.0.3/EventQueue.java:770)
	at java.awt.EventQueue$4.run(java.desktop@11.0.3/EventQueue.java:721)
	at java.awt.EventQueue$4.run(java.desktop@11.0.3/EventQueue.java:715)
	at java.security.AccessController.doPrivileged(java.base@11.0.3/Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(java.base@11.0.3/ProtectionDomain.java:85)
	at java.awt.EventQueue.dispatchEvent(java.desktop@11.0.3/EventQueue.java:740)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(java.desktop@11.0.3/EventDispatchThread.java:203)
	at java.awt.EventDispatchThread.pumpEventsForFilter(java.desktop@11.0.3/EventDispatchThread.java:124)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(java.desktop@11.0.3/EventDispatchThread.java:113)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.3/EventDispatchThread.java:109)
	at java.awt.EventDispatchThread.pumpEvents(java.desktop@11.0.3/EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.run(java.desktop@11.0.3/EventDispatchThread.java:90)

Found 1 deadlock.
```

**Comment by srowen** [comment]
Ah, do you by chance have an easy fix? I don't know much of anything about AWT/Swing. That app is not super useful and ancient, and I'd just as readily delete it

**Comment by emilianbold** [comment]
Like the tutorial says one's just supposed to surround the 3 lines in `main` with `SwingUtilities.invokeLater(new Runnable ....`

The app was actually quite useful to me! I couldn't quickly find an open source native app, but I did find zxing and the Swing app did the job (after I fixed this thing).

**Comment by srowen** [comment]
OK sounds good, done in https://github.com/zxing/zxing/commit/bdc7c26526ada2b7b9864d949b56d762f05c65ca Seems to work on Java 11 for me.

**Comment by emilianbold** [comment]
Thanks!
