### ISSUE TITLE
Hi @srowen Even downgrading the zxing version doesn't solves my issue, when using zxing 3.3.0 version I am getting this error -

### ISSUE THREAD

**Issue by nikkitagupta** [zxing/zxing#1577]
Hi @srowen Even downgrading the zxing version doesn't solves my issue, when using zxing 3.3.0 version I am getting this error -
Any specific version do you suggest to use ?

E  FATAL EXCEPTION: Thread-509
                                                                                                    Process: com.airwatch.androidagent, PID: 6064
                                                                                                    java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of ‘java.util.List’ appears in /system/framework/core-libart.jar)
                                                                                                    	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(SourceFile:16)
                                                                                                    	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(SourceFile:171)
                                                                                                    	at com.google.zxing.qrcode.detector.Detector.detect(SourceFile:5)
                                                                                                    	at com.google.zxing.qrcode.QRCodeReader.decode(SourceFile:6)
                                                                                                    	at com.google.zxing.MultiFormatReader.decodeInternal(SourceFile:13)
                                                                                                    	at com.google.zxing.MultiFormatReader.decodeWithState(SourceFile:9)
                                                                                                    	at com.airwatch.qrcode.DecodeHandler.getScanResult(SourceFile)
                                                                                                    	at com.airwatch.qrcode.DecodeHandler.decode(SourceFile)
                                                                                                    	at com.airwatch.qrcode.DecodeHandler.handleMessage(SourceFile)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    	at android.os.Looper.loop(Looper.java:148)
                                                                                                    	at com.airwatch.qrcode.d.run(SourceFile)

_Originally posted by @nikkitagupta in https://github.com/zxing/zxing/issues/1575#issuecomment-1335140048_

**Comment by srowen** [comment]
Don't reopen a duplicate. You need yet older versions perhaps; this looks like you are on a version that doesn't even support Java 8. Try 2.x
