### ISSUE TITLE
Wrong Aztec-Code Generation in 3.5.1 compared to 3.4.1

### ISSUE THREAD

**Issue by danWon12** [zxing/zxing#1583]
I create an Aztec code with the content "abc" and have the encoding hints set to AZTEC_LAYERS=5, ERROR_CORRECTION=33, CHARACTER_SET=UTF8 .
In the release 3.4.1 everything is ok, I can use a Scanner-App and get the expected result "abc".
In the release 3.5.1 the generated BitmapMatrix and therefore the Aztec code looks different. When I scan it with the same scanner I get the result "HCM QN".
Here is the method call:
```
hints:

AztecWriter().encode(
        "abc",
        BarcodeFormat.AZTEC,
        width,
        height,
        hints"
```
I am using the code/library in an Android app with Java.

Did something change in the default settings? Do you have similar observations?

![version341](https://user-images.githubusercontent.com/120590259/207665770-77a049ae-543a-4758-b0d2-cf77529fff1c.png)
![version351](https://user-images.githubusercontent.com/120590259/207665795-1c8f86f4-e254-4148-8e39-5e0711e98b0a.png)

**Comment by danWon12** [comment]
Thanks for the fast answer. I am really wondering what is going on. Depending on the charset I get different results in the new release. I mean I am just using "abc" as content. I tried three different scanner apps from the PlayStore and also GoogleLens. So I am pretty sure the encoded result is different between the two releases. I will continue testing and debugging. (I also tried some of the new Constants of the lib from here: https://github.com/zxing/zxing/discussions/1520 with no real outcome)

**Comment by 1170762202** [comment]
How can I resolve this Problem?

"main" prio=5 tid=1 Native
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x7293f7e8 self=0xb4000076684e3c00
  | sysTid=28151 nice=-10 cgrp=top-app sched=0/0 handle=0x7669b3a4f8
  | state=S schedstat=( 6060061375 646594029 8031 ) utm=475 stm=130 core=4 HZ=100
  | stack=0x7fd7d16000-0x7fd7d18000 stackSize=8188KB
  | held mutexes=
  native: #00 pc 00000000000dad78  /apex/com.android.runtime/lib64/bionic/libc.so (__ioctl+8)
  native: #01 pc 00000000000949e8  /apex/com.android.runtime/lib64/bionic/libc.so (ioctl+156)
  native: #02 pc 00000000000540b4  /system/lib64/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+292)
  native: #03 pc 00000000000552f0  /system/lib64/libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*)+64)
  native: #04 pc 0000000000055034  /system/lib64/libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+224)
  native: #05 pc 000000000004cb28  /system/lib64/libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+240)
  native: #06 pc 0000000000060140  /system/lib64/libcamera_client.so (android::hardware::BpCamera::stopPreview()+284)
  native: #07 pc 0000000000050d70  /system/lib64/libcamera_client.so (android::Camera::stopPreview()+172)
  native: #08 pc 0000000000191fe4  /system/lib64/libandroid_runtime.so (android_hardware_Camera_stopPreview(_JNIEnv*, _jobject*)+56)
  at android.hardware.Camera._stopPreview(Native method)
  at android.hardware.Camera.stopPreview(Camera.java:810)
  at com.yealink.zxing.core.CameraPreview.m(CameraPreview.java:5)
  at com.yealink.zxing.core.CameraPreview.surfaceDestroyed(CameraPreview.java:2)
  at android.view.SurfaceView.notifySurfaceDestroyed(SurfaceView.java:2089)
  at android.view.SurfaceView.updateSurface(SurfaceView.java:1305)
  at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:377)
  at android.view.View.dispatchWindowVisibilityChanged(View.java:15256)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1626)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1626)
  at android.view.ViewGroup.dispatchWindowVisibilityChanged(ViewGroup.java:1626)
  ... repeated 7 times
  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2776)
  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2265)
  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9019)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1142)
  at android.view.Choreographer.doCallbacks(Choreographer.java:946)
  at android.view.Choreographer.doFrame(Choreographer.java:875)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1127)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:210)
  at android.os.Looper.loop(Looper.java:299)
  at android.app.ActivityThread.main(ActivityThread.java:8118)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by Isigwe** [comment]
Thank YOU

**Comment by srowen** [comment]
I think it's because an ECI segment is added, yeah. that should be valid though, ECI segments are important. I wouldn't call that a bug but I can imagine apps not bothering to reads it

**Comment by danWon12** [comment]
You are absolutely right. It's a feature, I am closing the bug.
