### ISSUE TITLE
UnboundLocalError: local variable 'bc' referenced before assignment

### ISSUE THREAD

**Issue by zeusin** [zxing/zxing#1720]
Hello, 

I have installed zxing through pip.  this version is installed:
```shell
$zxing -V
zxing v1.0
using Java ZXing library version v3.5.1
```
I have different output running the command from ssh and from graphical....
If I run the command in gnome-terminal I get this output:

```shell
$zxing /alb0001.tiff 
/alb0001.tiff
=============
Traceback (most recent call last):
  File "/home/user/.local/bin/zxing", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/zxing/__main__.py", line 59, in main
    if not bc:
UnboundLocalError: local variable 'bc' referenced before assignment
```
 

but running the same command from ssh on another server, or even running ssh in same server  with 127.0.0.1 ( and even in the same gnome-terminal that was not working previously )  is working....
```shell
$ssh user@127.0.0.1 'zxing /alb0001.tiff'
user@127.0.0.1's password: 
/alb0001.tiff
=============
  Decoded TEXT barcode in PDF_417 format.
  Raw text:    '1234|000'
  Parsed text: '1234|000'
```

Host is almalinux 9.

Is there anything I can do to get the command running from a graphical terminal?

**Comment by zeusin** [comment]
This is not the right github. sorry.
