### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=11664; index=11664

### ISSUE THREAD

**Issue by zaheerrasheed** [zxing/zxing#1798]
Facing this crash randomly while scanning a barcode

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=11664; index=11664
at com.google.zxing.common.BitMatrix.get(BitMatrix.java:162)
at com.google.zxing.maxicode.MaxiCodeReader.extractPureBits(MaxiCodeReader.java:104)
at com.google.zxing.maxicode.MaxiCodeReader.decode(MaxiCodeReader.java:64)
at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
at com.budiyev.android.codescanner.Utils.decodeLuminanceSource(Utils.java:342)
at com.budiyev.android.codescanner.DecodeTask.decode(DecodeTask.java:75)
at com.budiyev.android.codescanner.Decoder$DecoderThread.run(Decoder.java:133)

**Comment by raphaelm** [comment]
We also see this a lot in our sentry recording

**Comment by srowen** [comment]
The current master / 3.5.4 release has both coordinates properly bounded:

int iy = top + Math.min((y * height + height / 2) / MATRIX_HEIGHT, height - 1);
int ix = left + Math.min(
    (x * width + width / 2 + (y & 0x01) * width / 2) / MATRIX_WIDTH,
    width - 1);
ix <= left + (width - 1) = right <= image.width - 1 ✓
iy <= top + (height - 1) = bottom <= image.height - 1 ✓
Both ix and iy are guaranteed to stay within the image BitMatrix, so BitMatrix.get can no longer read past bits.length. No further fix is needed — the exception is already fixed in any release at or after 3.4.0 (which includes the Aug 2021 width - 1 correction). The reporter's app is almost certainly pinned to an older zxing version (e.g., 3.3.x through a build before Aug 2021); upgrading to a current release eliminates the crash.
