### ISSUE TITLE
com.google.zxing.client.android.encode.QRCodeEncoder.encodeFromStreamExtra

### ISSUE THREAD

**Issue by JagdeepSingh28** [zxing/zxing#1809]
Got below crash event 

java.lang.SecurityException - Permission Denial: opening provider com.radio.pocketfm.app.helpers.GenericFileProvider from ProcessRecord{a76272f 3870:com.sample.app/u0a306} (pid=3870, uid=10306) that is not exported from UID 10268

Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.sample.app/com.google.zxing.client.android.encode.EncodeActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.fileexplorer.provider.FileExplorerFileProvider from ProcessRecord{78b40e4 15006:com.sample.app/u0a2247} (pid=15006, uid=12247) that is not exported from UID 10156
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4558)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4590)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:236)
       at android.app.ActivityThread.main(ActivityThread.java:8060)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
       
 What could be the possible fix for this ?

**Comment by JagdeepSingh28** [comment]
@srowen 
Isn't the security exception is coming in zxing Lib only ?

**Comment by srowen** [comment]
No, see the stack trace?
