### ISSUE TITLE
Aztec decoder fails: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vivekratansinha** [zxing/zxing#214]
I am using 3.1.1-SNAPSHOT of ZXing.
Encoded some UTF-8 text to Aztec Code using the library.
However, the Aztec Decoder fails to read the generated code.

The stacktrace is following:
java.lang.ArrayIndexOutOfBoundsException: 650
        at com.google.zxing.common.BitMatrix.get(BitMatrix.java:74)
        at com.google.zxing.aztec.decoder.Decoder.extractBits(Decoder.java:306)
        at com.google.zxing.aztec.decoder.Decoder.decode(Decoder.java:76)
        at com.google.zxing.aztec.AztecReader.decode(AztecReader.java:67)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
        at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:55)
        at net.atos.titan.matrixcode.MatrixCode.readMatrixCodeFromBufferedImage(MatrixCode.java:58)
        at net.atos.titan.matrixcode.MatrixCode.readMatrixCodeFromFile(MatrixCode.java:51)
        at net.atos.titan.matrixcode.MatrixCodeTest.testLoop(MatrixCodeTest.java:65)

**Comment by lovesitdoll** [comment]
Sha

**Comment by candyss9185** [comment]
Hi! I ran into the same exception. Did you find a solution?

**Comment by dklotz** [comment]
I am still getting the exact same exception, with exactly the same barcode posted here, with the current ZXing version 3.2.1, so this definitely not "closed".

**Comment by srowen** [comment]
@dklotz it's closed because nobody is providing a pull request to fix it. You can do so.

**Comment by dklotz** [comment]
Yes, but why on earth should someone provide a PR for a closed issue? A closed issue means the problem (!) does not exist any more (or is not reproducible etc.). The issue needs to be open so people can see it exist and there is one place to discuss possible solutions. I don't know anything about Aztec codes, so I don't think I can provide a fix for this in any sensible timeframe, but this issue needs to stay open until someone who does steps in.

**Comment by srowen** [comment]
_shrug_ it means I doubt anyone will ever do anything about it, since nobody has. I don't work on this project now. I wish there were a resolution status like "incomplete" but I suppose this comment serves that purpose.
