### ISSUE TITLE
IllegalArgumentException: Both dimensions must be greater than 0

### ISSUE THREAD

**Issue by ashishkhatri** [zxing/zxing#264]
I'm seeing this error upon launching the scanner via intent and then the app crashes, but only on certain devices.  It's happening on Note 10.1 (v4.4.2) and Note 4 (v4.4.4).  It's also happening on Galaxy Stellar (v4.1.2).  It's worked fine on Note 3 (v4.4.2) Galaxy S3 (v4.4.2) and multiple Motorola devices.

java.lang.IllegalArgumentException: Both dimensions must be greater than 0
    at com.google.zxing.common.BitMatrix.<init>(BitMatrix.java:54)
    at com.google.zxing.common.GlobalHistogramBinarizer.getBlackMatrix(GlobalHistogramBinarizer.java:101)
    at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:95)
    at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:92)
    at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:84)
    at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:195)
    at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:90)
    at com.google.zxing.client.android.DecodeHandler.decode(DecodeHandler.java:107)
    at com.google.zxing.client.android.DecodeHandler.handleMessage(DecodeHandler.java:63)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:146)
    at com.google.zxing.client.android.DecodeThread.run(DecodeThread.java:102)

**Comment by susussa** [comment]
Process: com.example.administrator.cainiaotuangou, PID: 32016
                                                                                          java.lang.IllegalArgumentException: Both dimensions must be greater than 0
                                                                                              at com.google.zxing.common.BitMatrix.<init>(BitMatrix.java:50)
                                                                                              at com.google.zxing.common.GlobalHistogramBinarizer.getBlackMatrix(GlobalHistogramBinarizer.java:91)
                                                                                              at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:86)
                                                                                              at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
                                                                                              at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
                                                                                              at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
                                                                                              at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
                                                                                              at com.uuzuche.lib_zxing.decoding.DecodeHandler.decode(DecodeHandler.java:86)
                                                                                              at com.uuzuche.lib_zxing.decoding.DecodeHandler.handleMessage(DecodeHandler.java:55)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                                              at com.uuzuche.lib_zxing.decoding.DecodeThread.run(DecodeThread.java:83)

**Comment by huuugh** [comment]
I got the same problem.Can u help me ?

**Comment by CinderellaCJ** [comment]
Are you resolve this problem？

**Comment by hkq325800** [comment]
@susussa you have use yipianfengye/android-zxingLibrary
there is a method "initDisplayOpinion()" in his ZApplication 
what you need to do is adding "extends ZApplication" in your own Application

**Comment by huuugh** [comment]
This solves my problem，thank you

**Comment by wsparse** [comment]
My problem also had resolved, thank you @susussa

**Comment by arronvera** [comment]
ZXingLibrary.initDisplayOpinion(this);

**Comment by KingOfSu** [comment]
Thankyou，are you chinese too?
