### ISSUE TITLE
Android 2.2 NoSuchMethodError: java.lang.String.isEmpty

### ISSUE THREAD

**Issue by jonasborggren** [zxing/zxing#293]
Using Android 2.2 I get an error.

```java
MultiFormatWriter writer = new MultiFormatWriter();
> BitMatrix result = writer.encode( contentsToEncode, BarcodeFormat.CODE_128, img_width, img_height, null ); <
```
```log
java.lang.NoSuchMethodError: java.lang.String.isEmpty
    at com.google.zxing.oned.OneDimensionalCodeWriter.encode(OneDimensionalCodeWriter.java:53)
    at com.google.zxing.oned.Code128Writer.encode(Code128Writer.java:61)
    at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:94)
```

The method isEmpty was added in Android 2.3 (API 9)
See more here http://developer.android.com/reference/java/lang/String.html#isEmpty()

**Comment by srowen** [comment]
Yes, this method did not exist in the Android SDK until 2.3. The current source code supports Android 4.0.3+ only.
