### ISSUE TITLE
Crash at launch

### ISSUE THREAD

**Issue by Rudloff** [zxing/zxing#355]
On my Geeksphone Revolution with CyanogenMod 11, Barcode Scanner always crashes at launch.
Here is the stacktrace:
```
E/AndroidRuntime( 5401): Process: com.google.zxing.client.android, PID: 5401
E/AndroidRuntime( 5401): java.lang.ArrayIndexOutOfBoundsException: src.length=1382400 srcPos=1382760 dst.length=808800 dstPos=621600 length=1200
E/AndroidRuntime( 5401): 	at java.lang.System.arraycopy(Native Method)
E/AndroidRuntime( 5401): 	at com.google.zxing.PlanarYUVLuminanceSource.getMatrix(PlanarYUVLuminanceSource.java:102)
E/AndroidRuntime( 5401): 	at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:70)
E/AndroidRuntime( 5401): 	at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
E/AndroidRuntime( 5401): 	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
E/AndroidRuntime( 5401): 	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
E/AndroidRuntime( 5401): 	at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
E/AndroidRuntime( 5401): 	at com.google.zxing.client.android.DecodeHandler.decode(DecodeHandler.java:82)
E/AndroidRuntime( 5401): 	at com.google.zxing.client.android.DecodeHandler.handleMessage(DecodeHandler.java:58)
E/AndroidRuntime( 5401): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5401): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 5401): 	at com.google.zxing.client.android.DecodeThread.run(DecodeThread.java:110)
```

**Comment by srowen** [comment]
That basically means the ROM doesn't represent correctly what the camera does. In particular it advertises some preview size, but doesn't send data in that size. I see this a lot when CM isn't fully customized for a driver.

**Comment by Rudloff** [comment]
It seems version 4.3.1 works correctly.
