### ISSUE TITLE
IndexOutOfBounds while decoding pdf417

### ISSUE THREAD

**Issue by feantury** [zxing/zxing#359]
While decoding an image using the mobile camera I am getting an IndexOutOfBounds exception. The full stack trace is:

Caused by: java.lang.ArrayIndexOutOfBoundsException: length=929; index=-247
            at com.google.zxing.pdf417.decoder.ec.ModulusGF.multiply(ModulusGF.java:105)
            at com.google.zxing.pdf417.decoder.ec.ModulusPoly.evaluateAt(ModulusPoly.java:99)
            at com.google.zxing.pdf417.decoder.ec.ErrorCorrection.decode(ErrorCorrection.java:53)
            at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.correctErrors(PDF417ScanningDecoder.java:553)
            at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decodeCodewords(PDF417ScanningDecoder.java:526)
            at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResultFromAmbiguousValues(PDF417ScanningDecoder.java:307)
            at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResult(PDF417ScanningDecoder.java:276)
            at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decode(PDF417ScanningDecoder.java:123)
            at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:87)
            at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:61)
            at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
            at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
            at nl.lotto.toto.ui.barcode.helpers.PreviewCallback$DecodeAsyncTask.doInBackground(PreviewCallback.java:99)
            at nl.lotto.toto.ui.barcode.helpers.PreviewCallback$DecodeAsyncTask.doInBackground(PreviewCallback.java:48)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

I am using currently Android 5.1 and zxing 3.2

**Comment by srowen** [comment]
Do you have any info to reproduce this like an example image? or a pull request?
