### ISSUE TITLE
DataMatrix encoder throws IllegalArgumentException in ZXing 3.2.0

### ISSUE THREAD

**Issue by wendykierp** [zxing/zxing#361]
Given the following encode method:

    public static BufferedImage encode(String contents, String format, int width, int height,    Map<EncodeHintType, ?> hints) {
        BufferedImage result = null;
        BarcodeFormat barcodeFormat = BarcodeFormat.valueOf(format);
        MultiFormatWriter barcodeWriter = new MultiFormatWriter();
        BitMatrix matrix = null;
        try {
            matrix = barcodeWriter.encode(contents, barcodeFormat, width, height, hints);
        } catch (WriterException ex) {
            return null;
        }
        result = MatrixToImageWriter.toBufferedImage(matrix);
        return result;
    }

Calling encode("1234", "DATA_MATRIX", 300, 300, null) throws 

    Exception in thread "main" java.lang.IllegalArgumentException: Can't find a symbol arrangement that matches the message. Data codewords: 2
	at com.google.zxing.datamatrix.encoder.SymbolInfo.lookup(SymbolInfo.java:148)
	at com.google.zxing.datamatrix.encoder.EncoderContext.updateSymbolInfo(EncoderContext.java:127)
	at com.google.zxing.datamatrix.encoder.EncoderContext.updateSymbolInfo(EncoderContext.java:122)
	at com.google.zxing.datamatrix.encoder.HighLevelEncoder.encodeHighLevel(HighLevelEncoder.java:189)
	at com.google.zxing.datamatrix.DataMatrixWriter.encode(DataMatrixWriter.java:84)
	at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:94)

**Comment by srowen** [comment]
Can you debug to see what's going on, and suggest a patch? this might be a straightforward one.

**Comment by srowen** [comment]
Hm, I think the change in https://github.com/zxing/zxing/pull/272 was actually incorrect and that's what's causing this. I see it too.

**Comment by srowen** [comment]
Resolved by https://github.com/zxing/zxing/pull/368 for now
