### ISSUE TITLE
java.lang.RuntimeException: setParameters failed

### ISSUE THREAD

**Issue by gauravnetzwelt** [zxing/zxing#364]
I am getting crash in one of my developed apps. The crash seems to be device specific as I am unable to reproduce the same at my end. I have listed the entire logcat and also the device model on which this crash occurred. Please help

Manufacturer: samsung
Model: GT-I9195

java.lang.RuntimeException: setParameters failed
	at android.hardware.Camera.native_setParameters(Native Method)
	at android.hardware.Camera.setParameters(Camera.java:1614)
	at com.google.zxing.client.android.camera.CameraConfigurationManager.setTorch(CameraConfigurationManager.java:337)
	at com.google.zxing.client.android.camera.CameraManager.setTorch(CameraManager.java:345)
	at com.google.zxing.client.android.CaptureFragment$1.onCheckedChanged(CaptureFragment.java:320)
	at android.widget.CompoundButton.setChecked(CompoundButton.java:136)
	at android.widget.CompoundButton.toggle(CompoundButton.java:91)
	at android.widget.CompoundButton.performClick(CompoundButton.java:103)
	at android.view.View$PerformClick.run(View.java:18044)
	at android.os.Handler.handleCallback(Handler.java:725)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5306)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by srowen** [comment]
Yeah, that's an error from the driver rather than the app.

**Comment by gauravnetzwelt** [comment]
You mean to say that the root cause lies within the samsung camera driver, if this is the case can we do something in this regard ?

**Comment by arpit999bicubic** [comment]
I woudn't agree that see here this might be the reason http://stackoverflow.com/questions/10605560/how-do-you-take-high-resolution-images-using-camera-takepicture/10605793#10605793
