### ISSUE TITLE
NullPointerException while decoding data that got from camera

### ISSUE THREAD

**Issue by butteryflycut** [zxing/zxing#529]
HI srowen:
I got this crash while using zxing on many hardware platforms.
Is it necessary to add null check to 'data' in DecodeHandler.decode?

java.lang.NullPointerException
	at com.zxing.decoding.DecodeHandler.decode(DecodeHandler.java:76)
	at com.zxing.decoding.DecodeHandler.handleMessage(DecodeHandler.java:57)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at com.zxing.decoding.DecodeThread.run(DecodeThread.java:82)

![image](https://cloud.githubusercontent.com/assets/7827582/12070129/cb68fcae-b09c-11e5-8655-5cd98d8a6029.png)

**Comment by srowen** [comment]
It's not possible to evaluate this without knowing which version of the code you are using; no it is not clear what is null. `data` can't be null unless you've modified the code or have a bad device. I have never seen this reported in the app crash reporter.

**Comment by butteryflycut** [comment]
OK. Thanks
