### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference

### ISSUE THREAD

**Issue by butteryflycut** [zxing/zxing#531]
Another one

java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference
	at com.zxing.camera.CameraManager.getFramingRect(CameraManager.java:223)
	at com.zxing.view.ViewfinderView.onDraw(ViewfinderView.java:74)
	at android.view.View.draw(View.java:15598)
	at android.view.View.updateDisplayListIfDirty(View.java:14487)
	at android.view.View.getDisplayList(View.java:14516)
	at android.view.View.draw(View.java:15307)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14479)
	at android.view.View.getDisplayList(View.java:14516)
	at android.view.View.draw(View.java:15307)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14479)
	at android.view.View.getDisplayList(View.java:14516)
	at android.view.View.draw(View.java:15307)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at android.view.View.updateDisplayListIfDirty(View.java:14479)
	at android.view.View.getDisplayList(View.java:14516)
	at android.view.View.draw(View.java:15307)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3536)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3329)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2816)
	at android.view.View.draw(View.java:15610)
	at android.widget.FrameLayout.draw(FrameLayout.java:658)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2795)
	at android.view.View.updateDisplayListIfDirty(View.java:14487)
	at android.view.View.getDisplayList(View.java:14516)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:279)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:285)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3048)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2857)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2468)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1329)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6780)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:826)
	at android.view.Choreographer.doCallbacks(Choreographer.java:622)
	at android.view.Choreographer.doFrame(Choreographer.java:591)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:812)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5692)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

![image](https://cloud.githubusercontent.com/assets/7827582/12070139/aed82eb0-b09d-11e5-9c24-df4706392a42.png)

**Comment by chetanrm** [comment]
i also face same error , searching json data in recyclerview

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.enkast.chetan.recycledjson, PID: 2362
                  java.lang.NullPointerException: Attempt to read from field 'java.lang.Object android.widget.Filter$FilterResults.values' on a null object reference
                      at com.enkast.chetan.recycledjson.adapters.CustomFilter.publishResults(CustomFilter.java:64)
                      at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
