### ISSUE TITLE
Java-SE CommandLineRunner no longer accepts files without full-path

### ISSUE THREAD

**Issue by l-dobrev** [zxing/zxing#539]
```
.../java ....j2se.CommandLineRunner file-to-decode.png
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:48)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.retainValid(CommandLineRunner.java:125)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:61)
```

Tested with:
* Java 1.7 from Oracle
* Java 1.8 from Oracle
* Java 1.7 from OpenJDK
* Java 1.8 from OpenJDK

Using ./file-to-decode.png yields the same exception.

ZXing: Commit 4e3abafe3008e02695f894eccf05f8257fca4ee9

**Comment by srowen** [comment]
Oops, thank you. Fixed now.
