### ISSUE TITLE
Camera error while trying to integrate Zxing as a standalone scanner

### ISSUE THREAD

**Issue by Ankit050** [zxing/zxing#579]
While using Nexus 5X, and setting the minimum SDK as 23 (in order to use the fingerprint scanner in an app having the barcode scanner), I tried to use Zxing library as a standalone scanner.

But I received an error message:
"Sorry The Android camera encountered a problem. You may need to restart the device."

The scanner works properly if the minimum SDK is reduced from 23.

**Comment by srowen** [comment]
You didn't provide any error message. It could relate to the new permissions framework.

**Comment by Ankit050** [comment]
There is no error message. But in the verbose section, I get this:
 An error occurred while connecting to camera: 0
CaptureActivity: Unexpected error initializing camera
 java.lang.RuntimeException: Fail to connect to camera service
                                                                                        at android.hardware.Camera.<init>(Camera.java:495)
                                                                                        at android.hardware.Camera.open(Camera.java:341)
                                                                                        at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:73)
                                                                                        at com.google.zxing.client.android.camera.CameraManager.openDriver(CameraManager.java:80)
                                                                                        at com.google.zxing.client.android.CaptureActivity.initCamera(CaptureActivity.java:723)
                                                                                        at com.google.zxing.client.android.CaptureActivity.surfaceCreated(CaptureActivity.java:423)
                                                                                        at android.view.SurfaceView.updateWindow(SurfaceView.java:583)
                                                                                        at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:177)
                                                                                        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2063)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by srowen** [comment]
That means a failure in the driver itself

**Comment by Ankit050** [comment]
So we would have to wait for any update from Android for the library to work?

**Comment by Ankit050** [comment]
Any other possible work around?
