### ISSUE TITLE
ArrayIndexOutOfBoundsException on files with only 1 pixel

### ISSUE THREAD

**Issue by AbdealiJK** [zxing/zxing#607]
When running on a file like https://commons.wikimedia.org/wiki/File:Pix.gif which has only 1 pixel, zxing throws an error:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
    at com.google.zxing.common.GlobalHistogramBinarizer.getBlackRow(GlobalHistogramBinarizer.java:71)
    at com.google.zxing.BinaryBitmap.getBlackRow(BinaryBitmap.java:66)
    at com.google.zxing.oned.OneDReader.doDecode(OneDReader.java:132)
    at com.google.zxing.oned.OneDReader.decode(OneDReader.java:54)
    at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
    at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:69)
    at com.google.zxing.multi.GenericMultipleBarcodeReader.doDecodeMultiple(GenericMultipleBarcodeReader.java:84)
    at com.google.zxing.multi.GenericMultipleBarcodeReader.decodeMultiple(GenericMultipleBarcodeReader.java:65)
    at com.google.zxing.client.j2se.DecodeWorker.decode(DecodeWorker.java:140)
    at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:75)
    at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:84)
```

Obviously barcodes will never exist in files that have 1 pixel, but zxing should not crash for it. (I'm running it on a lot of files, and this happened to be one of them)

The issue is that `localLuminance` in [GlobalHistogramBinarizer](https://github.com/zxing/zxing/blob/b189fd1d5629770b1ecbdf3e2f55a37776538957/core/src/main/java/com/google/zxing/common/GlobalHistogramBinarizer.java#L71) directly accesses the 2nd element (which does not exist).

**Comment by AbdealiJK** [comment]
Also, I opened this issue as documentation mainly, as I don't plan to provide a PR for it :)
You can close it (as per your policy).

**Comment by srowen** [comment]
No problem, this one is so trivial that I can easily reproduce and fix, so I'll just do it.

**Comment by AbdealiJK** [comment]
:D Awesome thanks ! :+1:
