### ISSUE TITLE
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Point.x' on a null object reference

### ISSUE THREAD

**Issue by David-Kuper** [zxing/zxing#655]
please help me to resolve the problem.
`java.lang.Throwable
                                                                                                  at com.taobao.fleamarket.zxing.camera.CameraConfigurationManager.getCameraResolution(CameraConfigurationManager.java:95)
                                                                                                  at com.taobao.fleamarket.zxing.camera.CameraManager.getFramingRectInPreview(CameraManager.java:265)
                                                                                                  at com.taobao.fleamarket.zxing.camera.CameraManager.buildLuminanceSource(CameraManager.java:314)
                                                                                                  at com.taobao.fleamarket.zxing.decoding.DecodeHandler.decode(DecodeHandler.java:81)
                                                                                                  at com.taobao.fleamarket.zxing.decoding.DecodeHandler.handleMessage(DecodeHandler.java:51)
                                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                  at android.os.Looper.loop(Looper.java:145)
                                                                                                  at com.taobao.fleamarket.zxing.decoding.DecodeThread.run(DecodeThread.java:81)`

**Comment by srowen** [comment]
It's an error in your app -- wrong place to ask.
