### ISSUE TITLE
zxing-javase: DecoderConfig's possibleFormats param requires a custom converter

### ISSUE THREAD

**Issue by aishahalim** [zxing/zxing#665]
JCommander can't infer custom types without a [diy-ed custom converter](http://jcommander.org/#Custom_types). Though List of Integer/String/Long are supported, List<BarcodeFormat> isn't.

source: https://github.com/zxing/zxing/blob/08e5431d995a88d443c06406520e62e2e0d02034/javase/src/main/java/com/google/zxing/client/j2se/DecoderConfig.java#L74

stacktrace from the lib built from source ([master](https://github.com/zxing/zxing/commits/e9e2bd280bcaeabd59d0f955798384fe6c018a6c)):

```
Caused by: com.beust.jcommander.ParameterException: Unknown option: --possible_formats AZTEC
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742) ~[javase-3.2.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.beust.jcommander.JCommander.parse(JCommander.java:282) ~[javase-3.2.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.beust.jcommander.JCommander.parse(JCommander.java:265) ~[javase-3.2.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.beust.jcommander.JCommander.<init>(JCommander.java:210) ~[javase-3.2.2-SNAPSHOT-jar-with-dependencies.jar:na]
        at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:52) ~[javase-3.2.2-SNAPSHOT-jar-with-dependencies.jar:na]
```

**Comment by srowen** [comment]
Hm, it seems to work for me. Well, there's a different problem here that you might have to be careful of but it's not  the same.

```
--possible_formats AZTEC test1.png
```

actually fails because it can't know that test1.png isn't a format name.

```
--possible_formats AZTEC --brief test1.png
```

Succeeds though. What's your command line? I think the declaration works OK as-is despite the doc at http://jcommander.org/#variable-arities

**Comment by aishahalim** [comment]
Wow, that was it! Even after "fixing" it by adding a converter, the `possibleFormats` variable picked up the main parameter's value as well, so that's really the problem I was running into.

It helped to add another flag after (as you demonstrated) or reorder it so that the main parameter (i.e. file/url) comes well before the possible formats flag in the arg list.

I'll take a look at why JCommander's unhappy with distinguishing between spaces in names v. spaces between args. Closing the issue.

**Comment by Cody-G** [comment]
Is there a dummy flag that we can add here so that wer'e not forced to set a flag whenever using `--possible_formats`?
