### ISSUE TITLE
Error Camera Scan 

### ISSUE THREAD

**Issue by CiccioCicc** [zxing/zxing#681]
Hi ,

I have a problem when run scan code.
This is error returned:

` Unexpected error initializing camera
                                                                                  java.lang.RuntimeException: Fail to connect to camera service
                                                                                      at android.hardware.Camera.<init>(Camera.java:563)
                                                                                      at android.hardware.Camera.open(Camera.java:371)
                                                                                      at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:64)
                                                                                      at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:85)
                                                                                      at com.google.zxing.client.android.camera.CameraManager.openDriver(CameraManager.java:83)
                                                                                      at com.google.zxing.client.android.CaptureActivity.initCamera(CaptureActivity.java:534)
                                                                                      at com.google.zxing.client.android.CaptureActivity.surfaceCreated(CaptureActivity.java:381)
                                                                                      at android.view.SurfaceView.updateWindow(SurfaceView.java:597)
                                                                                      at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:179)
                                                                                      at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2060)
                                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1112)
                                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6035)
                                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                                      at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5451)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Some advice?

**Comment by srowen** [comment]
Unfortunately it just means the camera driver hit an error. The app can't do anything

**Comment by CiccioCicc** [comment]
Yes, camera permission, was a silly problem ;). Thanks for your answer:)
