### ISSUE TITLE
zxing can not decode utf-8 encoded Chinese Characters  QR code 

### ISSUE THREAD

**Issue by waitinghu** [zxing/zxing#708]
Hi,
  I am using zxing Barcode Scanner , I found it can not decode a utf-8 encoded Chinese String.but I use some apps can decode the QR code correctly .such as wechat .Taobao.  if I encode the String with GBK to generate QR code，it works find 。 I traced the code in zxing/core/src/main/java/com/google/zxing/qrcode/decoder/DecodedBitStreamParser.java  .   I found the decoder goes to wrong mode.    mode = Mode.forBits(bits.readBits(4));  the result is Mode.KANJI .so it calls decodeKanjiSegment method next。the full messy code is “201610170063400000010285，麻譚冗浹逕伜哨譛肴��，兽药字（2012）050036112，蒙瑞普大地，0472-2209620”，and the right String is “201610170063400000010285，麻杏石甘口服液，兽药字（2012）050036112，蒙瑞普大地，0472-2209620”
> step 1 ： NUMERIC  mode  we got  “201610170063400000010285”
> step 2 ：BYTE  mode  we got  “，麻”
> step 3：KANJI mode  we got  “譚冗浹逕伜哨譛肴”  this step was wrong the String should be 杏石甘口....
> step 4： BYTE  mode  we got  “��，兽药字（2012）”  the messy code in this step i think is related with step 3.
> step 5：NUMERIC  mode  we got  “050036112”
> step 6：BYTE  mode  we got  “，蒙瑞普大地，0472-”
> step 7：NUMERIC  mode  we got  “2209620”

you can find the QR code picture： http://pan.baidu.com/s/1c1CsJNq

can you tell me why this happens？or actually  I can not encode the String with UTF-8 in the frist place？but why WeChat and taobao can decode it。

**Comment by srowen** [comment]
It definitely reads UTF-8, and therefore Chinese characters encoded in UTF-8. You would have to use BYTE mode, and would have to make sure it starts with an ECI segment that specifies UTF-8. Otherwise it's not guaranteed to work, and relies on the reader 'guessing' than it's UTF-8.

I can't see the barcode at your link so can't debug, but, that is likely the problem.

**Comment by waitinghu** [comment]
yes ,it works well at the most of time.but in this case it doesn't work. Same QR code pic which WetChat TaoBao can read,but zxing can not .I can't located the root cause of this issue.I think the problem it not the decoder try to "guessing" the encoding of the string.the problem is zxing goes to the wrong mode (it choose KANJI instead of BYTE mode,so it use `StringUtils.SHIFT_JIS` to decode directly which lead to a messy output). but I am sure there must be some reasons  lead two results from one QR code. 

By the way: how can I pass the barcode picture to you ,so you can debug it?

**Comment by waitinghu** [comment]
Hi,srowen

any update?

**Comment by srowen** [comment]
Update on what? I explained the problem already. The QR code you describe apparently does not include an ECI segment specifying UTF-8, so it is not valid. The TaoBao reader apparently always guesses a Chinese language encoding, which is fine, but not generally correct. The Barcode Scanner app must work correctly everywhere in the world. You need to fix your QR code.

**Comment by Psijic** [comment]
The same problem found with some Cyrillic QR codes. While default Google engine decode them successfully, zxing shows wrong  format.

**Comment by srowen** [comment]
You'd have to provide something more specific to investigate this. For example, I'm not clear this isn't just your terminal's settings or something.

**Comment by Psijic** [comment]
> You'd have to provide something more specific to investigate this. For example, I'm not clear this isn't just your terminal's settings or something.

[https://imgur.com/vTd7fsM](url)

This QR code maybe made wrong, but it should show Cyrillic and first letters should be `ST00011|Name=ТСЖ "Анохина"`
The charset used here is Windows-1251 / ISO-8859-1

**Comment by srowen** [comment]
The QR code does not contain an ECI segment that specifies a character encoding. It isn't UTF-8, so is (correctly) defaulted to ISO-8859-1. That wasn't the intended character set, but, the decoder can't know that. That's why it has to use UTF-8 encoding and/or specify the desired encoding with ECI. So, yes the QR code is wrong.

**Comment by Psijic** [comment]
Does it means if a QR code has unknown character encoding, the default charset for decoded code is ISO-8859-1 always? Why this charset is preferred?

**Comment by srowen** [comment]
No, because QR codes can include ECI segments to define the character encoding to be whatever you want.
Otherwise it's just guessed, though, if you use UTF-8 that will probably work.
Here it doesn't try to guess anything beyond ISO-8859-1, which is what the spec says to do.
Although I'd look at a pull request, the problem here is really that the QR code is incorrect in a few ways. If something gets it 'right' I think it's probably defaulting to your device's charset, which may be right for you but wrong if scanned elsewhere.

**Comment by Psijic** [comment]
Lens correctly recognize the text even if I make any language by default in Android settings. So, there should be a way to do it with zxing.

**Comment by vinukodi** [comment]
Can anyone help how to scan the QR code which is encoded with Shift_JIS/SJIS in Xamarin forms
?

![image](https://user-images.githubusercontent.com/78755115/107936299-7d299c80-6fa8-11eb-9ba8-bda38ea1ec37.png)

**Comment by srowen** [comment]
Works fine: https://zxing.org/w/decode?u=https%3A%2F%2Fci3.googleusercontent.com%2Fproxy%2Fi_Ungb3_SXbRzXjmMNrsny5eJMXvuQXLZ04vs-2smJws-uIXFTSssDl02cZGz5LQzRC-S236Ooh2bMPbwSQDJz7e7WxVQpkTs8z7NVXmj6zg4ZiaolirM1BK82jZtHUI47CvCuxJqYanB1s2Fakxw_sVPCW_kCCJ%3Ds0-d-e1-ft%23https%3A%2F%2Fuser-images.githubusercontent.com%2F78755115%2F107936299-7d299c80-6fa8-11eb-9ba8-bda38ea1ec37.png

**Comment by vinukodi** [comment]
> Works fine: https://zxing.org/w/decode?u=https%3A%2F%2Fci3.googleusercontent.com%2Fproxy%2Fi_Ungb3_SXbRzXjmMNrsny5eJMXvuQXLZ04vs-2smJws-uIXFTSssDl02cZGz5LQzRC-S236Ooh2bMPbwSQDJz7e7WxVQpkTs8z7NVXmj6zg4ZiaolirM1BK82jZtHUI47CvCuxJqYanB1s2Fakxw_sVPCW_kCCJ%3Ds0-d-e1-ft%23https%3A%2F%2Fuser-images.githubusercontent.com%2F78755115%2F107936299-7d299c80-6fa8-11eb-9ba8-bda38ea1ec37.png

I used below approach to scan the QR code, but didn't get scanned. Code details are posted in below link. can you suggest me is there anything I missed?

https://github.com/Bacon/BaconQrCode/issues/81

**Comment by meladgheath** [comment]
i have the same problems must my result as the follwoing م.ميادة الدلح but my result is ?.?????? why ? i use intellij idea

**Comment by meladgheath** [comment]
ok it's working fine but after wrapping my application it's not work and give me that : 
Exception in thread "JavaFX Application Thread" java.lang.ExceptionInInitializerError
        at org.softwareengine.merged.module@0.0.2/com.google.zxing.qrcode.encoder.Encoder.chooseMode(Unknown Source)
        at org.softwareengine.merged.module@0.0.2/com.google.zxing.qrcode.encoder.Encoder.encode(Unknown Source)
        at org.softwareengine.merged.module@0.0.2/com.google.zxing.qrcode.QRCodeWriter.encode(Unknown Source)
        at storeg@0.0.2/org.softwareengine.utils.ui.report.createQR(Unknown Source)
        at storeg@0.0.2/org.softwareengine.utils.ui.report.getDistrubumentReport(Unknown Source)
        at storeg@0.0.2/org.softwareengine.core.controller.noticController$13.handle(Unknown Source)
        at storeg@0.0.2/org.softwareengine.core.controller.noticController$13.handle(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Node.fireEvent(Unknown Source)
        at javafx.controls/javafx.scene.control.Button.fire(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
        at javafx.controls/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
        at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
        at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
        at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
        at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
        at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.nio.charset.UnsupportedCharsetException: EUC_JP
        at java.base/java.nio.charset.Charset.forName(Unknown Source)
        at org.softwareengine.merged.module@0.0.2/com.google.zxing.common.StringUtils.<clinit>(Unknown Source)
        ... 52 more

i use the image in the jasperreport

**Comment by srowen** [comment]
That is an unrelated question.

What JDK are you using? you can see that it says EUC_JP isn't a known encoding, but virtually any standard JDK supports this encoding
