### ISSUE TITLE
OOB Exception in PDF417 file

### ISSUE THREAD

**Issue by ened** [zxing/zxing#727]
This exception happened while the camera/scanner was idle (the camera was focussing the table, a black surface). This might have been caused by interference.

Unfortunately, this is hard to reproduce, at least there is a stack trace:

```
java.lang.ArrayIndexOutOfBoundsException: length=929; index=-488
    at com.google.zxing.pdf417.decoder.ec.ModulusGF.multiply(ModulusGF.java:105)
    at com.google.zxing.pdf417.decoder.ec.ModulusPoly.evaluateAt(ModulusPoly.java:99)
    at com.google.zxing.pdf417.decoder.ec.ErrorCorrection.decode(ErrorCorrection.java:53)
    at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.correctErrors(PDF417ScanningDecoder.java:556)
    at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decodeCodewords(PDF417ScanningDecoder.java:529)
    at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResultFromAmbiguousValues(PDF417ScanningDecoder.java:308)
    at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResult(PDF417ScanningDecoder.java:277)
    at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decode(PDF417ScanningDecoder.java:124)
    at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:87)
    at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:61)
    at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
    at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:55)
```

**Comment by srowen** [comment]
Yeah, that's tough to debug. I don't have any stack traces like this in the console, and I'm not clear how this can occur.

**Comment by ened** [comment]
I'm not sure a simple `Math.max(index, 0)` would be sufficient enough of a fix. But, negative indices will never work.  :-)
