### ISSUE TITLE
A crash IN BS.apk

### ISSUE THREAD

**Issue by TinyNiko** [zxing/zxing#754]
Hi, I find a crash when I sent a intent to com.google.zxing.client.android.book.SearchBookContentsActivity.
The crash logs generated on emulator  is in the following:

> 02-15 16:02:08.004 14748-14748/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.google.zxing.client.android, PID: 14748
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.zxing.client.android/com.google.zxing.client.android.book.SearchBookContentsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
                                                       at com.google.zxing.client.android.LocaleManager.isBookSearchUrl(LocaleManager.java:148)
                                                       at com.google.zxing.client.android.book.SearchBookContentsActivity.onCreate(SearchBookContentsActivity.java:106)
                                                       at android.app.Activity.performCreate(Activity.java:6323)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 

You can sent a intent to trigger this crash .

>  public void test()
    {
        Intent a = new Intent() ;
        a.setClassName("com.google.zxing.client.android", "com.google.zxing.client.android.book.SearchBookContentsActivity");
        a.setAction("com.google.zxing.client.android.SEARCH_BOOK_CONTENTS");
        a.putExtra("ISBN" , BigInteger.valueOf(1)) ;
        a.putExtra("QUERY","23333") ;
        startActivity(a);
    }

**Comment by srowen** [comment]
It's not meant for you to call externally, but, the problem is passing the wrong type for ISBN. It's a string.
