### ISSUE TITLE
crashes everytime 

### ISSUE THREAD

**Issue by notetienne** [zxing/zxing#767]
I get this everytime I click on my scan button

`FATAL EXCEPTION: main
                                                                                  Process: google.zxing.integration.android, PID: 24646
                                                                                  java.lang.NoSuchMethodError: No virtual method initiateScan()Landroid/app/AlertDialog; in class Lcom/google/zxing/integration/android/IntentIntegrator; or its super classes (declaration of 'com.google.zxing.integration.android.IntentIntegrator' appears in /data/app/google.zxing.integration.android-2/split_lib_dependencies_apk.apk:classes22.dex)
                                                                                      at com.example.etienne.folle_e.Produit.<init>(Produit.java:31)
                                                                                      at com.example.etienne.folle_e.MainActivity$1.onClick(MainActivity.java:73)
                                                                                      at android.view.View.performClick(View.java:5642)
                                                                                      at android.view.View$PerformClick.run(View.java:22338)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6209)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
03-07 18:48:41.627 24646-24646/google.zxing.integration.android D/AppTracker: App Event: crash
03-07 18:48:41.649 24646-24646/google.zxing.integration.android I/Process: Sending signal. PID: 24646 SIG: 9`

**Comment by srowen** [comment]
You have a mismatch somehow between what you compiled the app with and then what was packaged.
