### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by antoninovitale** [zxing/zxing#775]
android.content.res.Resources$NotFoundException: File res/raw/zxing_beep.ogg from drawable resource ID #0x7f08000c
	at android.content.res.Resources.openRawResourceFd(Resources.java:2322)
	at com.google.zxing.client.android.BeepManager.playBeepSound(SourceFile:112)
	at com.google.zxing.client.android.BeepManager.playBeepSoundAndVibrate(SourceFile:82)
	at com.journeyapps.barcodescanner.c$1.a(SourceFile:75)
	at com.journeyapps.barcodescanner.DecoratedBarcodeView$b.a(SourceFile:49)
	at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(SourceFile:52)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6117)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
	at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
	at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:443)
	at android.content.res.Resources.openRawResourceFd(Resources.java:2319)
	... 12 more

**Comment by srowen** [comment]
This isn't an app problem. SOmething's wrong with your Android or build.

**Comment by antoninovitale** [comment]
It happens in a number of devices (Galaxy S5, Galaxy A7, Galaxy Note4, Galaxy A5, Galaxy Tab2 10.1, Google Pixel, Galaxy Alpha, Galaxy S7, ...), I checked the apk file running "unzip -lv <file_name>.apk" and the zxing_beep.ogg is not compressed apparently.
I don't think it's a problem of the build, is there anyway to disable that beep programmatically?

**Comment by ismdcf** [comment]
@antoninovitale were you able to resolve the above issue.

**Comment by amithnair** [comment]
@antoninovitale I get the exact same issue. Was there a resolution to this problem.

**Comment by William2406** [comment]
@antoninovitale was there a solution to this problem?

**Comment by William2406** [comment]
I solve this problem by clicking on **"File> Invalided caches/ restart .. "**
