### ISSUE TITLE
CameraManager are created repeatedly to cause bug

### ISSUE THREAD

**Issue by pijie** [zxing/zxing#794]
SAMSUNG Galaxy s5  SM-G9008V android 4.2.2  

Exception:
Unexpected error initializing camera
                                                                   java.lang.RuntimeException: Fail to connect to camera service
                                                                       at android.hardware.Camera.native_setup(Native Method)
                                                                       at android.hardware.Camera.<init>(Camera.java:423)
                                                                       at android.hardware.Camera.open(Camera.java:375)
                                                                       at codebar.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:52)
                                                                       at codebar.camera.CameraManager.openDriver(CameraManager.java:87)
                                                                       at codebar.activity.CaptureActivity1.initCamera(CaptureActivity.java:312)
                                                                       at codebar.activity.CaptureActivity1.onResume(CaptureActivity.java:118)
                                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1198)
                                                                       at android.app.Activity.performResume(Activity.java:5530)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3048)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3087)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1345)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5579)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
                                                                       at dalvik.system.NativeStart.main(Native Method)

Reason:  onPause () - > onResume()  initCamera(SurfaceHolder)is called two times  but  cameManager instatnce is Different

**Comment by srowen** [comment]
Not sure what you're reporting here -- a problem in the Android Camera framework? the instance should be different.

**Comment by pijie** [comment]
When I scan successfully Click to jump to the browser,  CaptureActiviy call onPause(), and surfaceDestroyed(SurfaceHolder holder) called .but two method calls are not in strict order.
When I return from the browser, surfaceCreated(SurfaceHolder holder) is sometimes called causes the camera(hasSurface = false, initCamera(holder) ,hasSurface = true) to be initialized again and the onResume() is called .cameraManager and the camera (initCamera(holder)) is then initialized again . That causes the error dialog to pop up.
I have added judgment in the onResume(
           if (cameraManager == null){
            cameraManager = new CameraManager(getApplication());
        }
)

**Comment by pijie** [comment]
if (!hasSurface) {
      SurfaceView surfaceView = (SurfaceView) findViewById(R.id.preview_view);
      SurfaceHolder surfaceHolder = surfaceView.getHolder();
      surfaceHolder.removeCallback(this);
    }
This condition does not work

**Comment by srowen** [comment]
COuld you open a pull request or show exactly what change you're proposing?
