### ISSUE TITLE
PDF417ScanningDecoder发生StackOverflowError

### ISSUE THREAD

**Issue by sangx123** [zxing/zxing#817]
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.StackOverflowError
at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.detectCodeword(PDF417ScanningDecoder.java:419)
at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.getRowIndicatorColumn(PDF417ScanningDecoder.java:218)
at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decode(PDF417ScanningDecoder.java:64)
at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:87)
at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:61)
at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
at com.mykaishi.xinkaishi.activity.zxing.SZXingView.processData(SZXingView.java:44)
at com.mykaishi.xinkaishi.activity.zxing.SProcessDataTask.doInBackground(SProcessDataTask.java:60)
at com.mykaishi.xinkaishi.activity.zxing.SProcessDataTask.doInBackground(SProcessDataTask.java:39)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by sangx123** [comment]
发生的错误的概率并不是非常的高，但是一直存在的
