### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by ironmanTony** [zxing/zxing#829]
stack trace
```
java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@74accb0 rejected from java.util.concurrent.ThreadPoolExecutor@556f729[Running, pool size = 9, active threads = 9, queued tasks = 128, completed tasks = 379]

at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)

at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)

at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)

at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:607)

at com.myexample.idscan.camera.AutoFocusManager.onAutoFocus(Unknown Source)

at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1158)

at android.os.Handler.dispatchMessage(Handler.java:102)

at android.os.Looper.loop(Looper.java:171)

at android.app.ActivityThread.main(ActivityThread.java:5681)

at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)

at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
```

android:6.0.1

**Comment by ironmanTony** [comment]
maybe we can use another thread to handle autofocus

a demo use HandlerThread
```
final class AutoFocusManager implements Camera.AutoFocusCallback , Handler.Callback{

  private static final String TAG = AutoFocusManager.class.getSimpleName();

  private static final long AUTO_FOCUS_INTERVAL_MS = 2000L;
  private static final int  MSG_AUTO_FOCUS = 22;
  private static final Collection<String> FOCUS_MODES_CALLING_AF;
  static {
    FOCUS_MODES_CALLING_AF = new ArrayList<>(2);
    FOCUS_MODES_CALLING_AF.add(Camera.Parameters.FOCUS_MODE_AUTO);
    FOCUS_MODES_CALLING_AF.add(Camera.Parameters.FOCUS_MODE_MACRO);
  }

  private boolean stopped;
  private boolean focusing;
  private final boolean useAutoFocus;
  private final Camera camera;
  private Handler handler;
  private HandlerThread handlerThread;

  AutoFocusManager(Context context, Camera camera) {
    this.camera = camera;
    SharedPreferences sharedPrefs = PreferenceManager.getDefaultSharedPreferences(context);
    String currentFocusMode = camera.getParameters().getFocusMode();
    useAutoFocus =
        sharedPrefs.getBoolean(PreferencesActivity.KEY_AUTO_FOCUS, true) &&
        FOCUS_MODES_CALLING_AF.contains(currentFocusMode);
    Log.i(TAG, "Current focus mode '" + currentFocusMode + "'; use auto focus? " + useAutoFocus);
    if (useAutoFocus) {
      handlerThread = new HandlerThread("auto_focus_thread");
      handler = new Handler(handlerThread.getLooper(), this);
      handlerThread.start();
    }
    start();
  }

  @Override
  public synchronized void onAutoFocus(boolean success, Camera theCamera) {
    focusing = false;
    handler.sendEmptyMessageDelayed(MSG_AUTO_FOCUS, AUTO_FOCUS_INTERVAL_MS);
  }

  @Override
  public boolean handleMessage(Message msg) {
    if (msg != null) {
      switch (msg.what) {
        case MSG_AUTO_FOCUS:
          requestFocus();
          break;
      }
    }
    return false;
  }

  private void requestFocus() {
    if (!stopped && !focusing) {
      try {
        camera.autoFocus(this);
        focusing = true;
      } catch (RuntimeException re) {
        // Have heard RuntimeException reported in Android 4.0.x+; continue?
        Log.w(TAG, "Unexpected exception while focusing", re);
        // Try again later to keep cycle going
        handler.sendEmptyMessageDelayed(MSG_AUTO_FOCUS, AUTO_FOCUS_INTERVAL_MS);
      }
    }

  }


  synchronized void start() {
    if (useAutoFocus) {
      if (!stopped && !focusing) {
        handler.sendEmptyMessage(MSG_AUTO_FOCUS);
      }
    }
  }


  synchronized void stop() {
    stopped = true;
    if (useAutoFocus) {
      handlerThread.quit();
      // Doesn't hurt to call this even if not focusing
      try {
        camera.cancelAutoFocus();
      } catch (RuntimeException re) {
        // Have heard RuntimeException reported in Android 4.0.x+; continue?
        Log.w(TAG, "Unexpected exception while cancelling focusing", re);
      }
    }
  }

}
```
