### ISSUE TITLE
startPreview failed

### ISSUE THREAD

**Issue by ashuMobico** [zxing/zxing#894]
E/CameraInstance: Failed to start preview
                                                                                     java.lang.RuntimeException: startPreview failed
                                                                                         at android.hardware.Camera.startPreview(Native Method)
                                                                                         at com.journeyapps.barcodescanner.camera.CameraManager.startPreview(CameraManager.java:181)
                                                                                         at com.journeyapps.barcodescanner.camera.CameraInstance$5.run(CameraInstance.java:220)
                                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by srowen** [comment]
This is an error between your app and the camera driver

**Comment by ashuMobico** [comment]
My app is just calling :

IntentIntegrator integrator = new IntentIntegrator(this);
        integrator.setDesiredBarcodeFormats(IntentIntegrator.ONE_D_CODE_TYPES);
        integrator.setPrompt("Scan a barcode");
        integrator.setCameraId(0);  // Use a specific camera of the device
        integrator.setBeepEnabled(false);
        integrator.setBarcodeImageEnabled(true);
        integrator.initiateScan();

Is it possibly a camera driver error since i'm using this library with android things and raspberry pi ?

**Comment by srowen** [comment]
The error is from some other app though; look at the stack trace. And the error is also from the camera driver. This is not directly related to code in this project.
