### ISSUE TITLE
minSDK / java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

### ISSUE THREAD

**Issue by ligi** [zxing/zxing#937]
I just recently got a crash-report for my app:

```
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
at com.google.zxing.aztec.AztecWriter.a(SourceFile:42)
at com.google.zxing.MultiFormatWriter.a(SourceFile:102)
at com.google.zxing.MultiFormatWriter.a(SourceFile:49)
at org.ligi.passandroid.functions.BarcodeKt.b(SourceFile:62)
at org.ligi.passandroid.functions.BarcodeKt.a(SourceFile:27)
at org.ligi.passandroid.functions.BarcodeKt.a(SourceFile:12)
at org.ligi.passandroid.model.pass.BarCode.getBitmap(SourceFile:30)
at org.ligi.passandroid.ui.BarcodeUIController.<init>(SourceFile:31)
at org.ligi.passandroid.ui.PassViewActivity.f(SourceFile:49)
at org.ligi.passandroid.ui.PassViewActivity.onResumeFragments(SourceFile:130)
at android.support.v4.app.FragmentActivity.onPostResume(SourceFile:498)
at android.support.v7.app.AppCompatActivity.onPostResume(SourceFile:172)
at android.app.Activity.performResume(Activity.java:5134)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2611)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2649)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2122)
at android.app.ActivityThread.access$700(ActivityThread.java:134)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4867)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
at dalvik.system.NativeStart.main(Native Method)
```

Seems this was introduced in Android 4.4 - did not know zxing has a minSDK of 19 - usually the build of the app should break if a lib has a minSDK over the SDK of the app.

**Comment by srowen** [comment]
I'm not sure what you're reporting, but you are not running Java 7 here, and that has been required by the library for a long time. The Android app has a min SDK of 19, yes, and that provides Java 7 libraries. https://github.com/zxing/zxing/blob/master/android/AndroidManifest.xml

**Comment by ligi** [comment]
Hm - too bad - unfortunately the minSDK gets lost as you do not provide an aar - only a jar. Also the README does not state a minSDK of 19 - so this hit me by surprise. Not yet sure how to deal with this - would you accept a PR to work around this problem? As far as I see StandardCharsets is not really needed - one could also pass a constructed charset.

**Comment by srowen** [comment]
The Android app isn't a library, so there is no .aar. The manifest says minSDK=19, which is where that's declared. The Play Store obviously enforces that too automatically. I don't see a problem here. The whole project uses Java 7, which is fairly old now. Avoiding StandardCharsets doesn't change that.

**Comment by ligi** [comment]
I am using the zxing library in an android app.  As the library is delivered as a jar and not as an aar the minSDK is not enforced at compile time but it crashes for me at runtime in some cases. I am not willing to increase my minSDK to 19 as I still have plenty of users below 19.  Avoiding StandardCharsets would solve this problem for me as far as I see.

**Comment by srowen** [comment]
If you are concerned with this at compile time, you will want to build with Java 6. That would catch libraries with Java 7 byte code. In this respect it is like any library. You can check the build or release notes to see it needs Java 7 now. No, StandardCharsets is not the only difference. You would hit problems with AutoCloseable and more. You can go back to older versions of the code that didn't require Java 7.

**Comment by ligi** [comment]
Please at least make a mention in the change-log that this version needs minSDK 19 -
 from the side of an Android developer none of this here: https://github.com/zxing/zxing/releases reads as the lib became minSDK 19 - you just update the library and things crash on old devices that exist in the wild but not on the desks of most developers.

**Comment by srowen** [comment]
That's fine. SDK 19 was released over 4 years ago and isn't supported anymore even, but I take the point.
